services:
  # Redis - Message Broker
  redis:
    image: redis:7-alpine
    container_name: anb-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - anb-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Celery Worker
  celery_worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: anb-celery-worker
    restart: unless-stopped
    command: >
      celery -A app.workers.celery_app:celery_app worker
      --loglevel=info
      --concurrency=2
      --queues=video_processing,maintenance,rankings
      --hostname=worker@%h
    environment:
      - DATABASE_URL=mysql+aiomysql://ANBAdmin:ANB12345@ec2-54-236-19-23.compute-1.amazonaws.com:3306/anb_rising_stars
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    volumes:
      - ./storage:/storage
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - anb-network
    healthcheck:
      test: ["CMD", "celery", "-A", "app.workers.celery_app:celery_app", "inspect", "ping", "-d", "worker@%h"]
      interval: 30s
      timeout: 10s
      retries: 3

# Celery Beat
  celery_beat:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: anb-celery-beat
    restart: unless-stopped
    command: >
      celery -A app.workers.celery_app:celery_app beat
      --loglevel=info
      --schedule=/tmp/celerybeat-schedule
    environment:
      - DATABASE_URL=mysql+aiomysql://ANBAdmin:ANB12345@ec2-54-236-19-23.compute-1.amazonaws.com:3306/anb_rising_stars
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    volumes:
      - ./storage:/storage
      - ./logs:/app/logs
      - celery_beat_data:/tmp
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - anb-network

volumes:
  redis_data:
  celery_beat_data:

networks:
  anb-network:
    driver: bridge