# Imagen base con Python 3.12 (compatible con gevent y locust)
FROM python:3.12-slim

# Directorio de trabajo
WORKDIR /load-tests

# Copiar el archivo de pruebas
COPY load-tests/locustfile.py .

# Instalar dependencias
RUN pip install --no-cache-dir locust==2.41.5

# Exponer el puerto del dashboard de Locust
EXPOSE 8089

# Comando para ejecutar Locust
CMD ["locust", "-f", "locustfile.py", "--host", "http://api:8000"]
