services:
  # Nginx - Proxy Reverso
  nginx:
    image: nginx:1.25-alpine
    container_name: anb-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./storage:/storage:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api
    networks:
      - anb-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  anb-network:
    driver: bridge