services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: anb-nginx:latest
    container_name: anb-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./storage:/storage:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - anb-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  anb-network:
    external: true   # usamos una red creada previamente y compartida con la API